name: Build and Test

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot
          
      - name: Download and Install Export Templates
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
          unzip Godot_v4.4-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.4.stable
          mv templates/* ~/.local/share/godot/export_templates/4.4.stable/
          rm -f Godot_v4.4-stable_export_templates.tpz
          rm -rf templates

      - name: Import Assets & Regenerate Class DB
        working-directory: ./godot
        run: |
          godot --headless --editor --quit
          
      - name: Run GUT Tests
        working-directory: ./godot
        run: |
          godot -s --headless --path . addons/gut/gut_cmdln.gd
          
      - name: Linux/X11 Export
        working-directory: ./godot
        run: |
          mkdir -v -p ../build/linux
          godot --headless --export-release "Linux/X11" ../build/linux/starship-olympics
          
      - name: Mac OSX Export
        working-directory: ./godot
        run: |
          mkdir -v -p ../build/mac
          godot --headless --export-release "Mac OSX" ../build/mac/starship-olympics.zip
          
      - name: Windows Desktop Export
        working-directory: ./godot
        run: |
          mkdir -v -p ../build/windows
          godot --headless --export-release "Windows Desktop" ../build/windows/starship-olympics.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: starship-olympics-builds
          path: build 